
server:
  port: 8080
  address: 127.0.0.1
  tomcat:
    uri-encoding: UTF-8
  context-path: /
#  session:
#    # 会话是否持久化
#    persistent: false
#    # 会话超时
#    timeout: 10
#    # 会话数据位置
#    store-dir: /
#    # cookie设置
#    cookie:
#      max-age: 10
#  # 错误页面位置
  error:
    path: /error
#  # HTTP 压缩
#  compression:
#    enabled: true
#    min-response-size: 10


spring:
  datasource:
    url: jdbc:mysql://10.10.1.252/analysys
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true

  application:
    # 开启管理功能
    admin:
      enabled: true
  # autoconfigure:
    # 排除不需要的配置项
    # exclude:
  devtools:
    restart:
      # 排除资源修改实时重启
      exclude: static/**,public/**
      # 增加资源修改实时重启
      additional-paths: src/main/resources,src/main/java
      # 使用触发文件, 只有当该文件被修改时才会重新启动
      # trigger-file: src/main/resources/restart.txt
    remote:
      secret: mysecret
  jackson:
    date-format: yyyy-MM-dd(HH:mm:ss)
banner:
  charset: UTF-8
  # 配置banner地址
  image:
    location: file:C:/Users/Administrator/Pictures/soeasy.jpeg
security:
  basic:
    enabled: false


springfox:
  documentation:
    swagger:
      v2:
        host: localhost:8080
        path: /api